### ISSUE TITLE
оформление заказа

### ISSUE THREAD

**Issue by SeRGei93** [tokmakov/laravel-7-shop#1]
неплохо бы добавить регистрацию при оформлении заказа. 
если не авторизованный пользователь пытается оформить заказ, получаем ошибку

**Comment by tokmakov** [comment]
Это я накосячил, изначально для оформления заказа регистрация не обязательна. Ошибка происходит в шаблоне basket.checkout https://prnt.sc/vz0mug Исправить это легко
```
    <h1 class="mb-4">Оформить заказ</h1>
    @if ($profiles && $profiles->count())
        @include('basket.select', ['current' => $profile->id ?? 0])
    @endif
```
